---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - git
  - gnupg
  - tig
  - stow
  - asdf
  - antigen

asdf_plugins:
  - name: "java"
    repository: "https://github.com/halcyon/asdf-java.git"
    versions:
      - adoptopenjdk-17.0.0+35
    global: adoptopenjdk-17.0.0+35

  - name: "nodejs"
    repository: "https://github.com/asdf-vm/asdf-nodejs.git"
    versions:
      - 14.18.1
    global: 14.18.1

  - name: "python"
    repository: "https://github.com/danhper/asdf-python"
    versions:
      - 3.9.2
    global: 3.9.2

  - name: "ruby"
    repository: "https://github.com/asdf-vm/asdf-ruby"
    versions:
      - 2.6.3
    global: 2.6.3

  - name: "clojure"
    repository: "https://github.com/halcyon/asdf-clojure"
    versions:
      - 1.10.3.822
    global: 1.10.3.822

  - name: "terraform"
    repository: "https://github.com/Banno/asdf-hashicorp"
    versions:
      - 0.13.6
    global: 0.13.6

  - name: "flutter"
    repository: "https://github.com/oae/asdf-flutter"
    versions:
      - 2.0.6-stable
    global: 2.0.6-stable

  - name: "solidity"
    repository: "https://github.com/diegodorado/asdf-solidity"
    versions:
      - 0.8.4
    global: 0.8.4

  - name: "haskell"
    repository: "https://github.com/vic/asdf-haskell"
    versions:
      - 9.0.1
    global: 9.0.1

  - name: "golang"
    repository: "https://github.com/kennyp/asdf-golang"
    versions:
      - 1.16.5
    global: 1.16.5

  - name: "rust"
    repository: "https://github.com/code-lever/asdf-rust"
    versions:
      - 1.53.0
    global: 1.53.0

  - name: "scala"
    repository: "https://github.com/mtatheonly/asdf-scala"
    versions:
      - 3.0.2
    global: 3.0.2
