---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - zsh
  - git
  - gnupg
  - tig
  - stow
  - asdf
  - antigen
  - gh
  - awscli
  - watch
  - htop
  # feat request: aws session manager (for leapp)

homebrew_taps:
  - homebrew/cask

homebrew_cask_apps:
  - firefox
  - iterm2
  - visual-studio-code
  - obsidian
  - slack
  - spotify
  - google-chrome
  - brave-browser
  - leapp
  - drawio

asdf_plugins:
  - name: "java"
    repository: "https://github.com/halcyon/asdf-java.git"
    versions:
      - adoptopenjdk-17.0.0+35
    global: adoptopenjdk-17.0.0+35

  - name: "maven"
    repository: "https://github.com/halcyon/asdf-maven"
    versions:
      - 3.5.4
    global: 3.5.4

  - name: "nodejs"
    repository: "https://github.com/asdf-vm/asdf-nodejs.git"
    versions:
      - 16.14.2
    global: 16.14.2

  - name: "python"
    repository: "https://github.com/danhper/asdf-python"
    versions:
      - 3.10.2
    global: 3.10.2

  - name: "ruby"
    repository: "https://github.com/asdf-vm/asdf-ruby"
    versions:
      - 3.1.1
    global: 3.1.1

  - name: "clojure"
    repository: "https://github.com/halcyon/asdf-clojure"
    versions:
      - 1.10.3.822
    global: 1.10.3.822

  - name: "golang"
    repository: "https://github.com/kennyp/asdf-golang"
    versions:
      - 1.16.5
    global: 1.16.5

  - name: "rust"
    repository: "https://github.com/code-lever/asdf-rust"
    versions:
      - 1.53.0
    global: 1.53.0

  - name: "scala"
    repository: "https://github.com/mtatheonly/asdf-scala"
    versions:
      - 3.0.2
    global: 3.0.2
